# Generated by Django 2.1.11 on 2019-08-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20190826_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadgroup',
            name='leads',
        ),
    ]
