# Generated by Django 2.1.11 on 2019-08-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_leadgroup_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgroup',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='_leadgroup_leads_+', through='leads.Lead', to='account.Account'),
        ),
    ]
