# Generated by Django 2.1.9 on 2019-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
