# Generated by Django 2.1.9 on 2019-07-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20190622_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tiers',
            field=models.ManyToManyField(to='sponsors.Tier'),
        ),
        migrations.AddField(
            model_name='sponsorslistplugin',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sponsors.Tier'),
        ),
    ]
