# Generated by Django 2.1.4 on 2019-01-06 13:25
from django.conf import settings
from django.db import migrations


def create_homepage(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    homepage = FlatPage.objects.create(
        url='/',
        title='Home',
        template_name='home.html',
    )
    homepage.sites.add(Site.objects.get(pk=settings.SITE_ID))


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_homepage,
            migrations.RunPython.noop,
        ),
    ]
