# Generated by Django 2.1.9 on 2019-08-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190712_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceregistration',
            name='joining_sponsor_presentation',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='conferenceregistration',
            name='needs_translation_device',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='conferenceregistration',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('Men-S', "Men's S"), ('Men-M', "Men's M"), ('Men-L', "Men's L"), ('Men-XL', "Men's XL"), ('Men-2XL', "Men's 2XL"), ('Men-3XL', "Men's 3XL"), ('Men-4XL', "Men's 4XL"), ('Women-S', "Women's S"), ('Women-M', "Women's M"), ('Women-L', "Women's L"), ('Women-XL', "Women's XL"), ('Women-2XL', "Women's 2XL"), ('Women-3XL', "Women's 3XL"), ('Women-4XL', "Women's 4XL")], default='', max_length=30),
        ),
    ]
