# Generated by Django 2.1.9 on 2019-08-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190803_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceregistration',
            name='reservation_type',
            field=models.CharField(choices=[('default', 'Default'), ('sponsor', 'Sponsor'), ('grant-recipient', 'Grant Recipient'), ('internal', 'Internal')], default='default', max_length=30),
        ),
    ]
