# Generated by Django 2.1.9 on 2019-08-10 01:59

from django.db import migrations


def set_reservation_type(apps, schema_editor):
    ConferenceRegistration = apps.get_model("core", "ConferenceRegistration")
    (ConferenceRegistration
     .objects
     .filter(is_sponsor=True)
     .update(reservation_type='sponsor'))
    (ConferenceRegistration
     .objects
     .filter(is_grant_recipient=True)
     .update(reservation_type='grant-recipient'))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conferenceregistration_reservation_type'),
    ]

    operations = [
        migrations.RunPython(
            set_reservation_type,
            migrations.RunPython.noop,
        ),
    ]
