# Generated by Django 2.1.9 on 2019-07-08 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image

from ..models import AUDIENCE_CHOICES, ROOM_CHOICES


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_update_default_language'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('room', models.CharField(choices=ROOM_CHOICES, max_length=30)),
            ],
            options={
                'ordering': ('room',),
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Account')),
                ('picture', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('room', models.CharField(choices=ROOM_CHOICES, max_length=30)),
                ('slug', models.SlugField()),
                ('abstract', models.TextField()),
                ('description', models.TextField()),
                ('audience_level', models.CharField(choices=AUDIENCE_CHOICES, max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=15)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='schedule.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(help_text='In minutes')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='talks', to='schedule.TimeSlot'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='schedule.TimeSlot'),
        ),
    ]
