# Generated by Django 2.1.9 on 2019-07-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190717_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='is_keynote',
            field=models.BooleanField(default=False),
        ),
    ]
